name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Remplacez par votre branche principale.
  workflow_dispatch: # Permet un déclenchement manuel.

permissions:
  contents: write
  id-token: write # Nécessaire pour résoudre les erreurs liées au jeton.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1 # Correction : utilisation de la version stable actuelle.
      with:
        path: ./ # Déploie tous les fichiers.

    - name: Publish
      uses: actions/deploy-pages@v2
